[package]
name = "cli" 
version = "1.0.0" 
edition = "2021" 

[[bin]]
name = "cli" 
path = "src/main.rs"

[dependencies]
solana-sdk = ">=1.14, <1.17"
solana-client = ">=1.14, <1.17"
pool = {path = "../pool"}
swap = {path = "../swap"}
clap = { version = "4.0.0", features = ["derive"] }
