[package]
name = "swap"
version = "1.0.0"
edition = "2024"

[lib]
name = "swap"
path = "src/lib.rs"

[dependencies]
solana-sdk = ">=1.14, <1.17"
orca_whirlpools_core = "=2.0.0"
pool = {path = "../pool"}
