[package]
name = "mint" 
version = "1.0.0"
edition = "2021"

[lib]
name = "mint" 
path = "src/lib.rs"

[dependencies]
solana-sdk = ">=1.14, <1.17"
solana-client = ">=1.14, <1.17"
spl-token = {version = "=3.5.0", features = ["no-entrypoint"]}